# Generated by Django 2.2.4 on 2019-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimagedefault', models.ImageField(upload_to='skins')),
            ],
        ),
    ]
