# Generated by Django 2.1.7 on 2019-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_auto_20190410_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='login',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
