# Generated by Django 2.2.4 on 2019-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_pageskin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='backtouserpanel_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_council_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='panel_translator_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
