# Generated by Django 2.2.4 on 2019-09-14 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0003_auto_20190820_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileserve',
            options={'ordering': ['-pubdate']},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-pubdate']},
        ),
        migrations.AddField(
            model_name='blog',
            name='lastmod',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileserve',
            name='lastmod',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileserve',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='lastmod',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileserve',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
