# Generated by Django 2.2.4 on 2019-08-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_auto_20190630_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pubdate']},
        ),
    ]
