# Generated by Django 2.2.4 on 2019-09-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0005_auto_20190915_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formelement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_de',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_es',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_fr',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_hi',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_pl',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_ru',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='file_uk',
        ),
    ]
