# Generated by Django 2.2.4 on 2019-09-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_auto_20190915_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_hi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_pl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
