# Generated by Django 2.2.4 on 2019-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0009_auto_20190930_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageskin',
            name='welcomebanner',
            field=models.ImageField(blank=True, null=True, upload_to='skins'),
        ),
    ]
