# Generated by Django 2.2.4 on 2019-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0012_auto_20190930_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='pagemap',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='pagemap_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
