# Generated by Django 2.2.4 on 2019-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0013_auto_20190930_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='addblog',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addblog_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addfile_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='addinfo_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='editme_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
