# Generated by Django 2.2.4 on 2019-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0014_auto_20190930_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageskin',
            name='welcomebanner_small',
            field=models.ImageField(blank=True, null=True, upload_to='skins'),
        ),
    ]
