# Generated by Django 2.2.4 on 2020-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0016_auto_20191009_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageskin',
            name='eskslogo_main',
            field=models.ImageField(blank=True, null=True, upload_to='skins'),
        ),
    ]
