# Generated by Django 2.2.4 on 2019-08-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalBaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[(1, 'User'), (2, 'Council'), (3, 'Hotel'), (4, 'Translator')], max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('title_pl', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uk', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_hi', models.CharField(max_length=200, null=True)),
                ('descr', models.CharField(max_length=400)),
                ('descr_pl', models.CharField(max_length=400, null=True)),
                ('descr_en', models.CharField(max_length=400, null=True)),
                ('descr_de', models.CharField(max_length=400, null=True)),
                ('descr_fr', models.CharField(max_length=400, null=True)),
                ('descr_ru', models.CharField(max_length=400, null=True)),
                ('descr_uk', models.CharField(max_length=400, null=True)),
                ('descr_es', models.CharField(max_length=400, null=True)),
                ('descr_hi', models.CharField(max_length=400, null=True)),
            ],
            options={
                'ordering': ['portal'],
            },
        ),
        migrations.DeleteModel(
            name='CouncilBaseItem',
        ),
        migrations.DeleteModel(
            name='HotelBaseItem',
        ),
        migrations.DeleteModel(
            name='TranslatorBaseItem',
        ),
        migrations.DeleteModel(
            name='UserBaseItem',
        ),
    ]
