# Generated by Django 2.2.4 on 2019-08-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_auto_20190822_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellinkitem',
            options={'ordering': ['menu', 'position']},
        ),
        migrations.AlterModelOptions(
            name='translatorlinkitem',
            options={'ordering': ['menu', 'position']},
        ),
        migrations.AlterModelOptions(
            name='userlinkitem',
            options={'ordering': ['menu', 'position']},
        ),
    ]
