# Generated by Django 2.2.4 on 2019-08-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_auto_20190823_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councillinkitem',
            options={'ordering': ['menu', 'position']},
        ),
    ]
