# Generated by Django 2.2.4 on 2019-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_auto_20190823_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pl', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uk', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_hi', models.CharField(max_length=200, null=True)),
                ('quarter', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('comment_pl', models.TextField(blank=True, null=True)),
                ('comment_en', models.TextField(blank=True, null=True)),
                ('comment_de', models.TextField(blank=True, null=True)),
                ('comment_fr', models.TextField(blank=True, null=True)),
                ('comment_ru', models.TextField(blank=True, null=True)),
                ('comment_uk', models.TextField(blank=True, null=True)),
                ('comment_es', models.TextField(blank=True, null=True)),
                ('comment_hi', models.TextField(blank=True, null=True)),
                ('announcement', models.TextField(blank=True)),
                ('announcement_pl', models.TextField(blank=True, null=True)),
                ('announcement_en', models.TextField(blank=True, null=True)),
                ('announcement_de', models.TextField(blank=True, null=True)),
                ('announcement_fr', models.TextField(blank=True, null=True)),
                ('announcement_ru', models.TextField(blank=True, null=True)),
                ('announcement_uk', models.TextField(blank=True, null=True)),
                ('announcement_es', models.TextField(blank=True, null=True)),
                ('announcement_hi', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_start', 'date_end', 'quarter'],
            },
        ),
    ]
