# Generated by Django 2.2.4 on 2019-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_housingparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingparty',
            name='agreements1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='agreements2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='agreements3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='extra_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='faculty_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='formmap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='sh_preferences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingparty',
            name='userdata1',
            field=models.BooleanField(default=False),
        ),
    ]
