# Generated by Django 2.2.4 on 2019-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_auto_20190904_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingparty',
            name='userdata2',
            field=models.BooleanField(default=False),
        ),
    ]
