# Generated by Django 2.2.4 on 2019-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0008_housingparty_userdata2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingparty',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='housingparty',
            name='date_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
