# Generated by Django 2.2.4 on 2019-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0010_housingparty_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingparty',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingparty',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
