# Generated by Django 2.2.4 on 2019-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0014_auto_20190906_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='changeme_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
