# Generated by Django 2.2.4 on 2019-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0015_auto_20190906_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='active_parties_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='all_parties_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='future_parties_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='new_party_view_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='past_parties_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
