# Generated by Django 2.2.4 on 2019-09-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0016_auto_20190907_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='owner_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
