# Generated by Django 2.2.4 on 2019-09-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0017_auto_20190907_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_de',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_hi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='userinfo_uk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
