# Generated by Django 2.2.4 on 2019-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0018_auto_20190910_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='housing_party_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
