# Generated by Django 2.2.4 on 2019-09-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0019_auto_20190910_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingpartyitems',
            name='change_and_apply_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
