# Generated by Django 2.2.4 on 2019-10-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0020_auto_20190910_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTextTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortme', models.CharField(max_length=200)),
                ('sortme_pl', models.CharField(max_length=200, null=True)),
                ('sortme_en', models.CharField(max_length=200, null=True)),
                ('sortme_de', models.CharField(max_length=200, null=True)),
                ('sortme_fr', models.CharField(max_length=200, null=True)),
                ('sortme_ru', models.CharField(max_length=200, null=True)),
                ('sortme_uk', models.CharField(max_length=200, null=True)),
                ('sortme_es', models.CharField(max_length=200, null=True)),
                ('sortme_hi', models.CharField(max_length=200, null=True)),
                ('ascending', models.CharField(max_length=200)),
                ('ascending_pl', models.CharField(max_length=200, null=True)),
                ('ascending_en', models.CharField(max_length=200, null=True)),
                ('ascending_de', models.CharField(max_length=200, null=True)),
                ('ascending_fr', models.CharField(max_length=200, null=True)),
                ('ascending_ru', models.CharField(max_length=200, null=True)),
                ('ascending_uk', models.CharField(max_length=200, null=True)),
                ('ascending_es', models.CharField(max_length=200, null=True)),
                ('ascending_hi', models.CharField(max_length=200, null=True)),
                ('descending', models.CharField(max_length=200)),
                ('descending_pl', models.CharField(max_length=200, null=True)),
                ('descending_en', models.CharField(max_length=200, null=True)),
                ('descending_de', models.CharField(max_length=200, null=True)),
                ('descending_fr', models.CharField(max_length=200, null=True)),
                ('descending_ru', models.CharField(max_length=200, null=True)),
                ('descending_uk', models.CharField(max_length=200, null=True)),
                ('descending_es', models.CharField(max_length=200, null=True)),
                ('descending_hi', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=200)),
                ('realname_pl', models.CharField(max_length=200, null=True)),
                ('realname_en', models.CharField(max_length=200, null=True)),
                ('realname_de', models.CharField(max_length=200, null=True)),
                ('realname_fr', models.CharField(max_length=200, null=True)),
                ('realname_ru', models.CharField(max_length=200, null=True)),
                ('realname_uk', models.CharField(max_length=200, null=True)),
                ('realname_es', models.CharField(max_length=200, null=True)),
                ('realname_hi', models.CharField(max_length=200, null=True)),
                ('basename', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=200)),
                ('realname_pl', models.CharField(max_length=200, null=True)),
                ('realname_en', models.CharField(max_length=200, null=True)),
                ('realname_de', models.CharField(max_length=200, null=True)),
                ('realname_fr', models.CharField(max_length=200, null=True)),
                ('realname_ru', models.CharField(max_length=200, null=True)),
                ('realname_uk', models.CharField(max_length=200, null=True)),
                ('realname_es', models.CharField(max_length=200, null=True)),
                ('realname_hi', models.CharField(max_length=200, null=True)),
                ('basename', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
