# Generated by Django 2.2.4 on 2019-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0022_auto_20191016_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='change_forbidden_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='council_member_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='is_translator_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
