# Generated by Django 2.2.4 on 2019-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0023_auto_20191016_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admintexttools',
            name='mypermissions_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
