# Generated by Django 2.1.7 on 2019-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0003_auto_20190519_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, null=True)),
                ('login_pl', models.CharField(max_length=50, null=True)),
                ('login_en', models.CharField(max_length=50, null=True)),
                ('login_de', models.CharField(max_length=50, null=True)),
                ('login_fr', models.CharField(max_length=50, null=True)),
                ('login_ru', models.CharField(max_length=50, null=True)),
                ('login_uk', models.CharField(max_length=50, null=True)),
                ('login_es', models.CharField(max_length=50, null=True)),
                ('login_hi', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('password_pl', models.CharField(max_length=50, null=True)),
                ('password_en', models.CharField(max_length=50, null=True)),
                ('password_de', models.CharField(max_length=50, null=True)),
                ('password_fr', models.CharField(max_length=50, null=True)),
                ('password_ru', models.CharField(max_length=50, null=True)),
                ('password_uk', models.CharField(max_length=50, null=True)),
                ('password_es', models.CharField(max_length=50, null=True)),
                ('password_hi', models.CharField(max_length=50, null=True)),
                ('re_password', models.CharField(max_length=50, null=True)),
                ('re_password_pl', models.CharField(max_length=50, null=True)),
                ('re_password_en', models.CharField(max_length=50, null=True)),
                ('re_password_de', models.CharField(max_length=50, null=True)),
                ('re_password_fr', models.CharField(max_length=50, null=True)),
                ('re_password_ru', models.CharField(max_length=50, null=True)),
                ('re_password_uk', models.CharField(max_length=50, null=True)),
                ('re_password_es', models.CharField(max_length=50, null=True)),
                ('re_password_hi', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('name_pl', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
                ('name_fr', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_uk', models.CharField(max_length=50, null=True)),
                ('name_es', models.CharField(max_length=50, null=True)),
                ('name_hi', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('surname_pl', models.CharField(max_length=50, null=True)),
                ('surname_en', models.CharField(max_length=50, null=True)),
                ('surname_de', models.CharField(max_length=50, null=True)),
                ('surname_fr', models.CharField(max_length=50, null=True)),
                ('surname_ru', models.CharField(max_length=50, null=True)),
                ('surname_uk', models.CharField(max_length=50, null=True)),
                ('surname_es', models.CharField(max_length=50, null=True)),
                ('surname_hi', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('email_pl', models.CharField(max_length=50, null=True)),
                ('email_en', models.CharField(max_length=50, null=True)),
                ('email_de', models.CharField(max_length=50, null=True)),
                ('email_fr', models.CharField(max_length=50, null=True)),
                ('email_ru', models.CharField(max_length=50, null=True)),
                ('email_uk', models.CharField(max_length=50, null=True)),
                ('email_es', models.CharField(max_length=50, null=True)),
                ('email_hi', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
