# Generated by Django 2.1.7 on 2019-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0004_formitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitems',
            name='register',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
