# Generated by Django 2.1.7 on 2019-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0006_auto_20190703_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitems',
            name='admin_panel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='back',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
