# Generated by Django 2.1.7 on 2019-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0008_auto_20190703_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitems',
            name='action',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='action_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
