# Generated by Django 2.2.4 on 2019-08-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0010_auto_20190823_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarterClass',
        ),
    ]
