# Generated by Django 2.2.4 on 2019-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0011_delete_quarterclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitems',
            name='agree_international',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='agree_international_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
