# Generated by Django 2.2.4 on 2019-08-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0012_auto_20190828_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitems',
            name='or_if',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formitems',
            name='or_if_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
