# Generated by Django 2.2.4 on 2019-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0015_auto_20190830_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='building_no'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=25, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='local_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='local_no'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=30, verbose_name='street'),
        ),
    ]
