# Generated by Django 2.2.4 on 2019-08-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0017_user_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='special_case_docs_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formitems',
            name='spouse_cohabitant_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
