# Generated by Django 2.2.4 on 2019-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0019_auto_20190831_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformfields',
            name='deangroup',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
