# Generated by Django 2.2.4 on 2019-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0020_auto_20190831_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformfields',
            name='dataprocessing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='faculty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='if_room_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='international_placement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='mailinglist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='sh_choice1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='sh_choice2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='sh_choice3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='special_case_docs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformfields',
            name='spouse_cohabitant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
