# Generated by Django 2.2.4 on 2019-10-08 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0022_auto_20190916_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationformfields',
            options={'ordering': ['timeapplied', 'owner']},
        ),
        migrations.AlterModelOptions(
            name='quarterclassb',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='applicationformfields',
            name='timeapplied',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
