# Generated by Django 2.2.4 on 2019-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0024_auto_20191008_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformfields',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
