# Generated by Django 2.2.4 on 2019-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0026_auto_20191008_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformfields',
            name='timeapplied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
