# Generated by Django 2.2.4 on 2019-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0027_auto_20191008_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformfields',
            name='quarter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
