# Generated by Django 2.2.4 on 2019-10-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0028_applicationformfields_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthouse',
            options={'ordering': ['name']},
        ),
    ]
