# Generated by Django 2.2.4 on 2019-10-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0029_auto_20191008_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthouse',
            name='position',
        ),
    ]
