# Generated by Django 2.2.4 on 2019-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0031_auto_20191008_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=2, verbose_name='album'),
        ),
    ]
