# Generated by Django 2.2.4 on 2019-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0032_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_council',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User'), (2, 'Council'), (3, 'Council Admin'), (4, 'Superuser')], default=1, null=True),
        ),
    ]
