# Generated by Django 2.2.4 on 2019-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0033_auto_20191030_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthouse',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='studenthouse',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
